typography_spectrum: 0.8085389342159033
color:
  brandStrength: 0.8979605732019991
  lightness: 0.2468536465894431
  saturation: 0.7980372384190559
  rhythmicContrast: 0.6329672180581838
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
layout_spectrum: 0.19306628732010722
author:
  name: Brant Emery
  email: brant@rentabrant.com
  url: www.rentabrant.com
name: Feed the Word
navigation:
  - name: Main site
    url: 'http://www.rentabrant.com'
    type: external
title: B is for Brand
description: 'Everything you need to know about branding, business and becoming awesome.'
